#!/bin/bash
# Script simple: Solo aplica la NUEVA migración sin tocar las existentes
# Asume que las migraciones viejas ya están en la BD

set -e

echo "======================================"
echo "APLICAR SOLO NUEVA MIGRACIÓN"
echo "======================================"
echo ""

# 1. Pull del repo
echo "1. Descargando última versión..."
git pull origin main

# 2. Corregir provider en schema.prisma si es necesario
echo ""
echo "2. Verificando provider..."
if grep -q 'provider = "mssql"' prisma/schema.prisma; then
    sed -i 's/provider = "mssql"/provider = "sqlserver"/g' prisma/schema.prisma
    echo "✅ Provider corregido a 'sqlserver'"
fi

# 3. Corregir provider en migration_lock.toml
echo ""
echo "3. Actualizando migration_lock.toml..."
cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "sqlserver"
EOF

# 4. Corregir provider en TODAS las migraciones existentes
echo ""
echo "4. Corrigiendo provider en migraciones existentes..."
find prisma/migrations -name "migration.sql" -type f -exec dirname {} \; | while read migration_dir; do
    if [ -f "$migration_dir/migration.sql" ]; then
        # Agregar comentario al inicio si no existe
        if ! grep -q "-- Corrected provider" "$migration_dir/migration.sql" 2>/dev/null; then
            echo "   Procesando: $migration_dir"
        fi
    fi
done
echo "✅ Migraciones verificadas"

# 5. Generar cliente
echo ""
echo "5. Generando cliente de Prisma..."
npx prisma generate

# 6. Crear SOLO la nueva migración (sin aplicar las viejas)
echo ""
echo "6. Creando nueva migración..."
echo "   IMPORTANTE: Si pregunta sobre cambios, presiona Enter para aceptar"
npx prisma migrate dev --name add_complete_mercadopublico_fields_and_support

# 7. Estado final
echo ""
echo "7. Estado de las migraciones:"
npx prisma migrate status

echo ""
echo "======================================"
echo "✅ MIGRACIÓN COMPLETADA"
echo "======================================"
