#!/bin/bash
# Script para corregir el provider y ejecutar migración
# Usar SOLO si migrate-production.sh falla

set -e

echo "======================================"
echo "FIX PROVIDER Y MIGRACIÓN"
echo "======================================"
echo ""

# 1. Hacer pull forzado
echo "1. Haciendo pull forzado del repositorio..."
git fetch origin main
git reset --hard origin/main

# 2. Verificar y corregir el provider si es necesario
echo ""
echo "2. Verificando provider en schema.prisma..."
current_provider=$(grep "provider" prisma/schema.prisma | grep datasource -A 1 | tail -1 | awk '{print $3}' | tr -d '"')
echo "Provider actual: $current_provider"

if [ "$current_provider" != "sqlserver" ]; then
    echo "⚠️  Corrigiendo provider a 'sqlserver'..."
    sed -i 's/provider = "mssql"/provider = "sqlserver"/g' prisma/schema.prisma
    echo "✅ Provider corregido"
fi

# 3. Verificar migration_lock.toml
echo ""
echo "3. Verificando migration_lock.toml..."
if [ -f "prisma/migrations/migration_lock.toml" ]; then
    cat prisma/migrations/migration_lock.toml
else
    echo "Creando migration_lock.toml..."
    mkdir -p prisma/migrations
    cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "sqlserver"
EOF
    echo "✅ migration_lock.toml creado"
fi

# 4. Instalar dependencias
echo ""
echo "4. Instalando dependencias..."
npm install

# 5. Ejecutar migración
echo ""
echo "5. Ejecutando migración..."
npx prisma migrate deploy

# 6. Generar cliente
echo ""
echo "6. Generando cliente de Prisma..."
npx prisma generate

# 7. Estado final
echo ""
echo "7. Estado de las migraciones:"
npx prisma migrate status

echo ""
echo "======================================"
echo "✅ CORRECCIÓN Y MIGRACIÓN COMPLETADAS"
echo "======================================"
