#!/bin/bash
# Script para resetear migraciones y aplicar la nueva con el provider correcto
# IMPORTANTE: Este script asume que la base de datos YA TIENE el schema actual

set -e

echo "======================================"
echo "RESET MIGRACIONES Y DEPLOY"
echo "======================================"
echo ""

# 1. Pull forzado
echo "1. Descargando última versión del repositorio..."
git fetch origin main
git reset --hard origin/main

# 2. Backup del directorio de migraciones
echo ""
echo "2. Haciendo backup del directorio de migraciones..."
if [ -d "prisma/migrations" ]; then
    timestamp=$(date +%Y%m%d_%H%M%S)
    mv prisma/migrations "prisma/migrations_backup_$timestamp"
    echo "✅ Backup creado en: prisma/migrations_backup_$timestamp"
else
    echo "⚠️  No existe directorio de migraciones previo"
fi

# 3. Crear directorio de migraciones limpio
echo ""
echo "3. Creando directorio de migraciones limpio..."
mkdir -p prisma/migrations

# 4. Crear migration_lock.toml con provider correcto
echo ""
echo "4. Creando migration_lock.toml..."
cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "sqlserver"
EOF
echo "✅ migration_lock.toml creado con provider 'sqlserver'"

# 5. Verificar schema.prisma
echo ""
echo "5. Verificando schema.prisma..."
if grep -q 'provider = "mssql"' prisma/schema.prisma; then
    echo "⚠️  Corrigiendo provider en schema.prisma..."
    sed -i 's/provider = "mssql"/provider = "sqlserver"/g' prisma/schema.prisma
    echo "✅ Provider corregido"
else
    echo "✅ Provider ya es 'sqlserver'"
fi

# 6. Crear migración baseline desde la BD existente
echo ""
echo "6. Creando migración baseline desde la base de datos existente..."
echo "   (Esto sincroniza Prisma con el estado actual de la BD)"
npx prisma migrate resolve --applied "0_init" || true

# 7. Marcar todas las tablas existentes como migradas
echo ""
echo "7. Marcando estado actual de la BD..."
npx prisma db pull
echo "✅ Schema sincronizado con la base de datos"

# 8. Generar cliente de Prisma
echo ""
echo "8. Generando cliente de Prisma..."
npx prisma generate

# 9. Crear la nueva migración con los campos adicionales
echo ""
echo "9. Creando migración con campos adicionales de Mercado Público..."
npx prisma migrate dev --name add_complete_mercadopublico_fields_and_support --create-only

# 10. Aplicar la migración
echo ""
echo "10. Aplicando migración a la base de datos..."
npx prisma migrate deploy

# 11. Estado final
echo ""
echo "11. Estado final de las migraciones:"
npx prisma migrate status

echo ""
echo "======================================"
echo "✅ RESET Y MIGRACIÓN COMPLETADOS"
echo "======================================"
echo ""
echo "Siguiente paso: Reiniciar el servidor"
echo "  pm2 restart app_licitaciones"
